# Func's plugin for JumpBox* - Prison
# Version 1.0
#
# MySQL Keys

user: 'root'
password: '9eCWqIjPwR'
host: 'localhost'
database: 'data'
port: 3306

# Messages Configuration

info: '&7[&ai&7] '
error: '&7[&c!&l&6*&7] '
fatal_error: '&7[&c!&l&6**&7] '

# Blocks

prices:
  list: "DIRT SAND GRAVEL STONE COBBLESTONE COAL_ORE IRON_ORE LOG LOG_2 GOLD_BLOCK"
  DIRT: 0.1
  SAND: 25
  GRAVEL: 300
  STONE: 1000
  COBBLESTONE: 333
  COAL_ORE: 200
  IRON_ORE: 200
  LOG: 0.1
  LOG_2: 0.1
  GOLD_BLOCK: 100

# Needs

needs:
  amount: 3
  1:
    effect: 'SLOW'
    message: 'Вам срочно нужно в туалет!'
  2:
    effect: 'CONFUSION'
    message: 'Вам необходимо помыться!'
  3:
    effect: 'SLOW_DIGGING'
    message: 'Скорее идите в кровать!'

# Mobs

rats:
  amount: 2
  1:
    x: -360
    y: 103
    z: 73
  2:
    x: -360
    y: 103
    z: 75

# Drops

no_drop: 'WOOD_PICKAXE WOOD_AXE'
drop:
  items: 8
  1:
    material: 'APPLE'
    name: '&cЯблоко'
    max_amount: 12
  2:
    material: 'WOOD_PICKAXE'
    name: 'Деревянная кирка 1 уровня'
    max_amount: 1
  3:
    material: 'APPLE'
    name: '&cЯблоко'
    max_amount: 12
  4:
    material: 'APPLE'
    name: '&cЯблоко'
    max_amount: 12
  5:
    material: 'APPLE'
    name: '&cЯблоко'
    max_amount: 12
  6:
    material: 'APPLE'
    name: '&cЯблоко'
    max_amount: 12
  7:
    material: 'APPLE'
    name: '&cЯблоко'
    max_amount: 12
  8:
    material: 'APPLE'
    name: '&cЯблоко'
    max_amount: 12

# Levels

level:
  1:
    price: 100
    blocks: 1000
  2:
    price: 1000
    blocks: 10000
  3:
    price: 10000
    blocks: 100000

# Items

items:
  кирка:
    1:
      name: 'Деревянная кирка 1 уровня'
      material: 'WOOD_PICKAXE'
      cost: 35
      effect:
      blocks:
    2:
      name: 'Деревянная кирка 2 уровня'
      material: 'WOOD_PICKAXE'
      cost: 50
      effect:
        enchantment: 'DIG_SPEED'
        level: 1
      blocks:
        DIRT: 30
        SAND: 30
        GRAVEL: 30
    3:
      name: 'Деревянная кирка 3 уровня'
      material: 'WOOD_PICKAXE'
      cost: 100
      effect:
        enchantment: 'DIG_SPEED'
        level: 2
      blocks:
        DIRT: 30
        SAND: 30
        GRAVEL: 30
    4:
      name: 'Деревянная кирка 4 уровня'
      material: 'DIAMOND_PICKAXE'
      cost: 200
      effect:
        enchantment: 'DIG_SPEED'
        level: 1000
      blocks:
        DIRT: 30
        SAND: 30
        GRAVEL: 30

  меч:
  лук:

  шлем:
  доспехи:
  поножи:
  ботинки:

# Mines

mines_value: 2

mines:
  1:
    name: '%Шахта 1%'
    material: 'DIRT'
    min_level: 1
    pvp: false
    h: 20
    diametr: 20
    x: -300
    y: 100
    z: 100
    time: 50
    types: 'DIRT SAND GRAVEL'
    tpx: 1
    tpy: 1
    tpz: 1
  2:
    name: '%Шахта 2%'
    material: 'STONE'
    min_level: 8
    pvp: false
    h: 30
    diametr: 30
    x: -350
    y: 100
    z: 100
    time: 180
    types: 'STONE STONE COBBLESTONE COAL_ORE STONE IRON_ORE'
    tpx:
    tpy:
    tpz:

