# Func's plugin for Topeon* - Prison
# Version 1.0
#
# MySQL Keys

user: 'root'
password: '1234567890q'
host: 'topeontest.playvds.online'
database: 'data'
port: 2452

# Messages Configuration

info: '&7[&ai&7] '
error: '&7[&c!&l&6*&7] '
fatal_error: '&7[&c!&l&6**&7] '

# Items

items:
    - '
    %Предмет 1%.
      %Материал предмета%.
      %Название предмета%.
      %Максимальный уровень%.
        %1 уровень : цена : Энчант%.
        %2 уровень : цена : Энчант%.
        %3 уровень : цена : Энчант%.'
    - '
    %Предмет 2%.
      %Материал предмета%.
      %Название предмета%.
      %Максимальный уровень%.
        %1 уровень : цена : Энчант%.
        %2 уровень : цена : Энчант%.
        %3 уровень : цена : Энчант%.'
    - '
    %Предмет 3%.
      %Материал предмета%.
      %Название предмета%.
      %Максимальный уровень%.
        %1 уровень : цена : Энчант%.
        %2 уровень : цена : Энчант%.
        %3 уровень : цена : Энчант%.'
    - '
    %Предмет 4%.
      %Материал предмета%.
      %Название предмета%.
      %Максимальный уровень%.
        %1 уровень : цена : Энчант%.
        %2 уровень : цена : Энчант%.
        %3 уровень : цена : Энчант%.'
# Mines

mines_value: 3

#   Название/Минимайльный уровень/Наличие ПВП/Высота/Диаметр/x/y/z/Респаун в секундах/Количество блоков

mine1: '%Шахта 1%/1/false/20/20/-300/100/100/50/3/DIRT;SAND;GRAVEL'
mine2: '%Шахта 2%/5/false/30/30/-350/100/100/180/6/STONE;STONE;COBBLESTONE;COAL_ORE;STONE;IRON_ORE'
mine3: '%Шахта 3%/11/false/30/30/-250/100/100/180/6/NETHERRACK;NETHERRACK;NETHERRACK;LAVA;NETHERRACK;QUARTZ_ORE'
