# Func's plugin for Topeon* - Prison
# Version 1.0
#
# MySQL Keys

user: 'root'
password: '1234567890q'
host: 'topeontest.playvds.online'
database: 'data'
port: 2452

# Messages Configuration

info: '&7[&ai&7] '
error: '&7[&c!&l&6*&7] '
fatal_error: '&7[&c!&l&6**&7] '

# Items

items:
    - '
    %Предмет 1%.
      %Материал предмета%.
      %Название предмета%.
      %Максимальный уровень%.
        %1 уровень : цена : Энчант%.
        %2 уровень : цена : Энчант%.
        %3 уровень : цена : Энчант%.'
    - '
    %Предмет 2%.
      %Материал предмета%.
      %Название предмета%.
      %Максимальный уровень%.
        %1 уровень : цена : Энчант%.
        %2 уровень : цена : Энчант%.
        %3 уровень : цена : Энчант%.'
    - '
    %Предмет 3%.
      %Материал предмета%.
      %Название предмета%.
      %Максимальный уровень%.
        %1 уровень : цена : Энчант%.
        %2 уровень : цена : Энчант%.
        %3 уровень : цена : Энчант%.'
    - '
    %Предмет 4%.
      %Материал предмета%.
      %Название предмета%.
      %Максимальный уровень%.
        %1 уровень : цена : Энчант%.
        %2 уровень : цена : Энчант%.
        %3 уровень : цена : Энчант%.'
# Mines

mines:
    - '
    %Шахта 1%.
      %Минимальный уровень%.
      %Наличие PVP%.
      %Количесво типов блоков%.
        %1 тип : процент%.
        %2 тип : процент%.
        %3 тип : процент%.'
    - '
    %Шахта 2%.
      %Минимальный уровень%.
      %Наличие PVP%.
      %Количесво типов блоков%.
        %1 тип : процент%.
        %2 тип : процент%.
        %3 тип : процент%.'
    - '
    %Шахта 3%.
      %Минимальный уровень%.
      %Наличие PVP%.
      %Количесво типов блоков%.
        %1 тип : процент%.
        %2 тип : процент%.
        %3 тип : процент%.'
    - '
    %Шахта 4%.
      %Минимальный уровень%.
      %Наличие PVP%.
      %Количесво типов блоков%.
        %1 тип : процент%.
        %2 тип : процент%.
        %3 тип : процент%.'

# Blocks

GRASS: 'Mannahara'
STONE: 'Stone'
LOG: 'Log'
DIRT: 'Zyne'
SAND: 'rugofluk'
COBBLESTONE: 'JuanFco'
