main: prison.PrisonMain
author: func
version: 1.37
website: https://vk.com/funcid
name: Prison
description: '§cХочу стать девочкой-волшебницей.'
commands:
  mine:
    usage:
  upgrade:
    usage:
  level:
    usage:
  gift:
    usage:
  deposit:
    usage:
  fraction:
    usage:
  base:
    usage:
  shop:
    usage: