main: prison.PrisonMain
author: func
version: 1.32
name: Prison
commands:
  mine:
    usage:
  upgrade:
    usage:
  level:
    usage:
  gift:
    usage:
  deposit:
    usage:
  fraction:
    usage:
  base:
    usage:
  shop:
    usage: